version: "3"

networks:
  default:

services:
  pizzola-core:
    container_name: pizzola-core
    build:
      context: pizzola-core
    ports:
      - "8080:8080"
    networks:
      default:
        aliases:
          - pizzola.docker.local